name: purchase_product_optional_17_18_target

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data

  odoo:
    build: .
    depends_on:
      - db
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
    shm_size: '2gb'
    ports:
      - "8178:8069"
    volumes:
      - ..:/mnt/extra-addons/purchase_product_optional
      - ./logs:/var/log/odoo
    command: >
      odoo -d purchase_product_optional_qa
      -i purchase_product_optional
      --addons-path=/usr/lib/python3/dist-packages/odoo/addons,/mnt/extra-addons
      --logfile=/var/log/odoo/odoo_qa.log

volumes:
  db-data:
